### ISSUE TITLE
2.2.6的问题和疑惑

### ISSUE THREAD

**Issue by lubyxu** [gwuhaolin/dive-into-webpack#11]
1、你好，最近阅读了你的书。发现里面关于output.libraryTarget = "global" 的说法：『编写的库将通过window赋值給指定的名称』。是不是有问题？
2、另外，不太明白为什么CommonJS2 要在CommonJS上增加一个module。这个很困惑

**Comment by gwuhaolin** [comment]
> 1、你好，最近阅读了你的书。发现里面关于output.libraryTarget = "global" 的说法：『编写的库将通过window赋值給指定的名称』。是不是有问题？

我的失误，应该是 **编写的库将通过 `global` 被赋值给通过 `library` 指定的名称，即把库挂载到 `global` 上**

**Comment by gwuhaolin** [comment]
> 2、另外，不太明白为什么CommonJS2 要在CommonJS上增加一个module。这个很困惑

https://stackoverflow.com/questions/16383795/difference-between-module-exports-and-exports-in-the-commonjs-module-system
