### ISSUE TITLE
有小伙伴说，一般出书了，就是过时了

### ISSUE THREAD

**Issue by WisestCoder** [gwuhaolin/dive-into-webpack#13]
你们怎么看👀

**Comment by gwuhaolin** [comment]
目前为止Webpack是最成熟、使用最多的构建工具，并且还会保持一段时间。

本书的目的不是介绍前沿、大多数人所不知道的技术，而是把知识进行整理，系统性的全面介绍webpack。

**Comment by IVANLEE99** [comment]
过时又如何，能解决现在目前需求就好啦
就算过时，至少我们也使用过
即使如gulp 或 grunt 一样又如何
有了这一波经验
下一个更好的东西自然更容易上手
因为思想指导实践
汲取思想吧
