### ISSUE TITLE
模块热替换notwork

### ISSUE THREAD

**Issue by gaoguoxin** [gwuhaolin/dive-into-webpack#15]
在书的1.6.2这一节，书中说:要开启模块热替换，我们只需在启动DevServer时带上--hot参数,重启DeverServer后再去更新文件就能体验到模块热替换的神奇了。
我按照书中所说，做了一遍，发现页面没有更新
在浏览器的console中得到了如下信息
```javascript
[WDS] App updated. Recompiling...
[WDS] App hot update...
```
看到hot update，我知道已经进行热更新了，问题是页面内容的更新是通过重新加载页面实现的。需要在入口文件中加入以下代码，但是关于这一点，作者却没有加上
```javascript
if(module.hot){
  module.hot.accept()
}
```
另外，我觉得作者应该提醒一下读者,在启动DevServer的时候加上--hot参数,实际上与在webpack.config.js中加上这句的效果是一样的:
```javascript
const webpack = require('webpack')
plugins:[
  new webpack.HotModuleReplacement()
]
```
综上，一句话,要实现模块热替换功能有两种实现途径:
1、在npm 的scripts里面启动DevServer的时候手动加上--hot参数
2、在webpack.config.js中加入这句:
```javascript
const webpack = require('webpack')
plugins:[
  new webpack.HotModuleReplacement()
]
```
做完了以上任意的配置后，还需要在入口文件加上
```javascript
if(module.hot){
  module.hot.accept()
}
```

**Comment by gwuhaolin** [comment]
书中是有提到加`module.hot.accept()`的，这是书中的描述：

---

可见补丁中包含了 `main.css` 文件新编译出来 CSS 代码，网页中的样式也立刻变成了源码中描述的那样。

但当你修改 `main.js` 文件时，会发现模块热替换没有生效，而是整个页面被刷新了，为什么修改 `main.js` 文件时会这样呢？

Webpack 为了让使用者在使用了模块热替换功能时能灵活地控制老模块被替换时的逻辑，可以在源码中定义一些代码去做相应的处理。

把的 `main.js` 文件改为如下：
```js
import React from 'react';
import { render } from 'react-dom';
import { AppComponent } from './AppComponent';
import './main.css';

render(<AppComponent/>, window.document.getElementById('app'));

// 只有当开启了模块热替换时 module.hot 才存在
if (module.hot) {
  // accept 函数的第一个参数指出当前文件接受哪些子模块的替换，这里表示只接受 ./AppComponent 这个子模块
  // 第2个参数用于在新的子模块加载完毕后需要执行的逻辑
  module.hot.accept(['./AppComponent'], () => {
    // 新的 AppComponent 加载成功后重新执行下组建渲染逻辑
    render(<AppComponent/>, window.document.getElementById('app'));
  });
}
```
其中的 `module.hot` 是当开启模块热替换后注入到全局的 API，用于控制模块热替换的逻辑。

现在修改 `AppComponent.js` 文件，把 `Hello,Webpack` 改成 `Hello,World`，你会发现模块热替换生效了。
但是当你编辑 `main.js` 时，你会发现整个网页被刷新了。为什么修改这两个文件会有不一样的表现呢？

当子模块发生更新时，更新事件会一层层往上传递，也就是从 `AppComponent.js` 文件传递到 `main.js` 文件，
直到有某层的文件接受了当前变化的模块，也就是 `main.js` 文件中定义的 `module.hot.accept(['./AppComponent'], callback)`，
这时就会调用 `callback` 函数去执行自定义逻辑。如果事件一直往上抛到最外层都没有文件接受它，就会直接刷新网页。

那为什么没有地方接受过 `.css` 文件，但是修改所有的 `.css` 文件都会触发模块热替换呢？
原因在于 `style-loader` 会注入用于接受 CSS 的代码。

**Comment by xiaoqiang730730** [comment]
@gwuhaolin 我现在直接下载 4.6 章的代码，直接运行npm run dev:hot，没有热更新。
![jietu20180626-101742](https://user-images.githubusercontent.com/8445916/41885401-6afe5e46-792a-11e8-972c-4fa99f52da2a.gif)
