### ISSUE TITLE
关于tree shaking

### ISSUE THREAD

**Issue by gaoguoxin** [gwuhaolin/dive-into-webpack#16]
在4.10.2，接入tree shaking中,作者讲到了需要修改.bablerc文件,以让babel保留es6的模块化语句。因为使用tree shaking 的前提就是一定要在模块中使用es6的模块化语句，如果babel将模块化语句转换成es5的语法,则tree shaking 不会像预期的那样工作。

我亲自试了一下,本地并没有.babelrc文件，是一样可以进行tree shaking的，可能是因为webpack的版本问题，我使用的是3.10.0

**Comment by gwuhaolin** [comment]
如果你只使用了ES6模块化语法 import export 而没使用其它诸如 async await、extend class 等语法，是能做到不要.babelrc文件的，原因在于Webpack3内置了对ES6模块化语法的支持。

如果你使用了诸如 async await、extend class 等语法就需要通过Babel转换，而默认情况下Babel也会把ES6模块化语法转换为ES5模块化语法。

**Comment by zhongjie-chen** [comment]
@gwuhaolin 没有babelrc设置，是新版本babel 默es6模块吗

**Comment by gwuhaolin** [comment]
babel默认的配置是会把ES6模块化语法转换成ES5语法的，webpack是无法针对ES5模块化语法做tree shaking的
