### ISSUE TITLE
开个勘误 issue 吧

### ISSUE THREAD

**Issue by 52cik** [gwuhaolin/dive-into-webpack#17]
比如：<http://webpack.wuhaolin.cn/2%E9%85%8D%E7%BD%AE/2-9%E5%A4%9A%E7%A7%8D%E9%85%8D%E7%BD%AE%E7%B1%BB%E5%9E%8B.html>
"需要写量个文件"

"量个" 应该是 "两个"

**Comment by fwgood** [comment]
1.1节
“ES6 模块化是国际标准化组织 ECMA 提出的 JavaScript 模块化规范，它在语言的层面上实现了模块化。”
其中“ECMA”是“欧洲计算机制造联合会”的英文缩写

**Comment by fwgood** [comment]
"devServer.host 配置项用于配置 DevServer 服务监听的端口，默认使用 8080 端口。 如果 8080 端口已经被其它程序占有就使用 8081，如果 8081 还是被占用就使用 8082，以此类推。"
port误写为host

**Comment by gwuhaolin** [comment]
谢谢大家，都已修正
