### ISSUE TITLE
如何在线阅读

### ISSUE THREAD

**Issue by zhoufeifan** [gwuhaolin/dive-into-webpack#18]
我想看电子书，可以通过付费开放gitbook 的阅读权限吗，买制作书比较麻烦。

**Comment by fwgood** [comment]
在线阅读不是开放的么，如果你指的的是广告弹窗无法去除的话，屏蔽掉.gitbook-plugin-modal 这个div就好，但是想支持作者的话还是尽量买纸质书吧

**Comment by zhoufeifan** [comment]
@fwgood 好的，谢谢了

**Comment by gwuhaolin** [comment]
see https://github.com/gwuhaolin/dive-into-webpack/issues/2
