### ISSUE TITLE
vscode 怎么调试webpack？

### ISSUE THREAD

**Issue by cike8899** [gwuhaolin/dive-into-webpack#19]
launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "name": "Launch Program",
      "program": "${workspaceFolder}/node_modules/webpack/bin/webpack.js"
    }
  ]
}

```
F5启动后 webpack.config.js里的断点是灰色的
![image](https://user-images.githubusercontent.com/8089971/35368281-8ba0fc10-01bd-11e8-8a2f-6b59d89d0ec9.png)
走不到断点

**Comment by gwuhaolin** [comment]
vscode我不是很熟悉，我用的webstorm，这个和编辑器有关，熟悉的同学可以解答一下。

**Comment by adoer** [comment]
https://code.visualstudio.com/docs/nodejs/nodejs-debugging
