### ISSUE TITLE
在线阅读，购买纸质书的dialog不能关闭的吗？

### ISSUE THREAD

**Issue by zeromake** [gwuhaolin/dive-into-webpack#2]
http://webpack.wuhaolin.cn/4%E4%BC%98%E5%8C%96/4-3%E4%BD%BF%E7%94%A8HappyPack.html

看了开发者工具也没有关闭按钮，控制台倒是有报错：
``` 
Uncaught TypeError: Cannot read property 'split' of undefined
    at c (theme.js:4)
    at l (theme.js:4)
    at HTMLDivElement.f (theme.js:4)
    at HTMLDivElement.dispatch (theme.js:2)
    at HTMLDivElement.m.handle (theme.js:2)
```
现在先把dialog的js屏蔽了

**Comment by chengzhiping** [comment]
可以先暂时这样操作，把遮罩层css改为display:none,  再把body的height改为一个足够的高度，就可以看了。点击任何目录都不会有问题。

**Comment by mafeifan** [comment]
简单粗暴法，在console里执行
` setInterval(() => document.querySelector('.gitbook-plugin-modal').style.width = 0, 1000)`

**Comment by zeromake** [comment]
@mafeifan 这个浏览资源不是这样浪费的啊， 还不如直接加入屏蔽规则： `http://webpack.wuhaolin.cn/gitbook/gitbook-plugin-modal/index.js`

**Comment by mafeifan** [comment]
@zeromake 你这个更好。issue就此关闭吧。喜欢的话还是买纸质书吧。作者写书不易。

**Comment by zeromake** [comment]
@mafeifan 问题是该书已经对我没用了，里面的都会，也就优化部分有些有用，不想买本吃灰书，也许推荐给我部门的那些前端更好

**Comment by gwuhaolin** [comment]
谢谢大家对本书的关注～
弹窗广告是出版社的要求，我正在努力向出版社申请完全在线开放此书。
习惯电子版的读者可以使用以上方法暂时先讲究阅读下，再次感想大家对本书的关注，希望能帮到到家。

**Comment by xqk1** [comment]
如果可以的话，可以开发电子版购买 @gwuhaolin
