### ISSUE TITLE
第三章是不是可以删掉？

### ISSUE THREAD

**Issue by gaoguoxin** [gwuhaolin/dive-into-webpack#20]
第三章占用了大约100页来告诉读者怎样接各种loader,但是讲的又是一带而过的感觉，感觉意义不大，所以我觉得可以省略掉第三章。

**Comment by gwuhaolin** [comment]
第三章对于熟练Webpack的人来说可能会显得多余，但对于刚入门的新人来说确实需要这些重实战的教程去引导它们快速跑通。

我会重新检查一遍第三章没讲清楚的章节，尽量补上一带而过的地方。
