### ISSUE TITLE
我觉得Flow不能算Javascript的超集

### ISSUE THREAD

**Issue by anymost** [gwuhaolin/dive-into-webpack#21]
首先感谢作者的贡献。
作者在文中写到：
“Flow
Flow 也是 JavaScript 的一个超集，它的主要特点是为 JavaScript 提供静态类型检查，和 TypeScript 相似但更灵活，可以让你只在需要的地方加上类型检查。“
我觉得Flow不能算Javascript的超集吧，就像Flow官网上写到的：“Flow： A Static Type Checker For Javascript“

**Comment by fwgood** [comment]
赞同，Flow和Typescript定义不同，Flow只是一个可选的类型系统，而不是一门语言

**Comment by gwuhaolin** [comment]
这是一个很抽象的问题～
