### ISSUE TITLE
3.10管理多页应用的问题

### ISSUE THREAD

**Issue by xiaoxiaoaobama** [gwuhaolin/dive-into-webpack#22]
3.10管理多页应用的问题
我下载了zip后只有build构建命令，想请教下开发环境需要怎样配置？

**Comment by gwuhaolin** [comment]
3.10管理多页应用的核心在于教会你为多个单元应用输出HTML。

开发环境使用 webpack-dev-server 即可，参见  [1-6 使用 DevServer](http://webpack.wuhaolin.cn/1%E5%85%A5%E9%97%A8/1-6%E4%BD%BF%E7%94%A8DevServer.html)，再把代码压缩去掉。
