### ISSUE TITLE
不给看了？

### ISSUE THREAD

**Issue by Richar-Dada** [gwuhaolin/dive-into-webpack#24]
不给看了？

**Comment by Moretai** [comment]
@Richar-Dada 如果你想看的话,身为前端你应该可以办到。哈哈哈 但是 不建议。毕竟它属于作者。

**Comment by Richar-Dada** [comment]
@Moretai 有点意思

**Comment by gwuhaolin** [comment]
参照 https://github.com/gwuhaolin/dive-into-webpack/issues/2
