### ISSUE TITLE
浩麟哥，有考虑把书升级到webpack4.0版本吗？

### ISSUE THREAD

**Issue by BengBu-YueZhang** [gwuhaolin/dive-into-webpack#25]
书里的代码很多已经在4.0的环境下，跑不起来了

**Comment by jiang-xiche** [comment]
+1 懵逼了一下午才发现版本不一致

**Comment by jiang-xiche** [comment]
+1 懵逼了一下午才发现版本不一致

**Comment by charlie-opatatong** [comment]
说说我花钱买作者实体书后的感受吧：

相信作者初衷还是好的。我是一个新学webpack的小白，实体书出来我就买的，奔着网上说的国内第一本介绍webpack的宣传去买的。

结果才买来没几个月，我就发现作者在gitbook上免费把这本书公开了，当时感觉有点。。。，那我当初花好几十是何苦呢。

然后拿着书和gitbook上一对比，代码很多还不一样了，书上的例子到使用extract-text-webpack-plugin来独立打包css就已经不能用了，gitbook上的代码也一样不能用。而且也没有开放评论，这坑让我一个初学者咋个整。本来是想照着书上例子动手练习的，结果反而无端添加更多成本啊，现在都是只能度娘谷歌各种错误。。导致现在我怀疑我买这书到底帮我啥了。。。

建议作者既然免费把书和代码放到网上了，能搞个带评论功能之类的不，至少有点互动吧，这样说不定有些错误，别的读者已经解决了，方便后来者一起学习啊。我相信这是作者初衷，四不四o(*￣︶￣*)o

**Comment by MuYunyun** [comment]
支持大佬，希望能更新下去

**Comment by gwuhaolin** [comment]
- webpack4支持正在更新中；
- 网上挂免费图书是为了方便大家阅读和拷贝代码；

**Comment by klfzlyt** [comment]
支持大佬

**Comment by Zohner** [comment]
支持大佬，对webpack4支持这一块，哪里可以获到最新的通知，webpack都是从这本书学的，怒赞！

**Comment by ma450921** [comment]
前端技术不适合做纸质书，当书完成的那一刻，书中介绍的技术已经过时了，更何况印刷，出售到读者手里。所以买纸质书就当支持作者了，还是看电子版吧。

**Comment by funwithes** [comment]
我才买的📖，还没看就过时了!!

**Comment by jiang-xiche** [comment]
哈哈 v3会了 就不怕v4了





| |
jiangxc163
邮箱：jiangxc163@163.com
|

Signature is customized by Netease Mail Master

在2018年07月01日 21:00，Samuel Chia 写道：

我才买的📖，还没看就过时了!!

**Comment by duohudie** [comment]
@gwuhaolin 大佬，请问现在http://webpack.wuhaolin.cn/%E5%89%8D%E8%A8%80.html这个文档是版本几的，更新4的了吗？

**Comment by LuckyMona** [comment]
不明白那些说过时的，每一章节都有完整代码提供，你复制作者提供的代码里面的各种版本就好了

**Comment by diyao** [comment]
可以放个收付款二维码，纸质书买了不能更新，但着实想支持下作者。

**Comment by bi-kai** [comment]
希望作者更新4.x版本的文档，我们都支持你

**Comment by simbawus** [comment]
请教下，webpack4 多个chunks 引用同一个modules里的某个export，导致这个modules的tree shaking失效，大家怎么应对这个问题的？[webpack  Issues](https://github.com/webpack/webpack/issues/4453)

**Comment by MazinForever** [comment]
社会大佬了.前端的工具技术知识推广, 真的这种git book是最棒的,谢谢,至于纸质书可能用于摸摸质感 很好..

**Comment by qinhx** [comment]
有好多代码可能因为更新用不了，比如管理多个单页面应用，无法输出html文件

**Comment by diyao** [comment]
大家要知足啊，“师傅领进门，修行靠个人”。
与其等待作者升级到4分享出来，不如自己折腾折腾。

**Comment by johe-a** [comment]
建议大家看下这个https://webpack.js.org/plugins/extract-text-webpack-plugin/，这里有webpack4 plugins的改动和用法
