### ISSUE TITLE
动态entry有哪些应用场景呢？

### ISSUE THREAD

**Issue by WhiteYin** [gwuhaolin/dive-into-webpack#27]
> 假如项目里有多个页面需要为每个页面的入口配置一个 Entry ，但这些页面的数量可能会不断增长，则这时 Entry 的配置会受到到其他因素的影响导致不能写成静态的值。其解决方法是把 Entry 设置成一个函数去动态返回上面所说的配置

能详细讲讲有哪些原因导致不能写成静态的值吗？搜关键字“webpack 动态entry”也没找到。

**Comment by gwuhaolin** [comment]
一个项目由多个SPA组成，每个SPA一个entry，随着业务的迭代，SPA的数量++，对应的entry也需要变化。

**Comment by WhiteYin** [comment]
@gwuhaolin 了解了，感谢！
