### ISSUE TITLE
dllplugins 优化

### ISSUE THREAD

**Issue by xuchao008** [gwuhaolin/dive-into-webpack#28]

**Comment by xuchao008** [comment]
请问作者，webpack Dllplugins 优化，生成的文件可以自动集成在生成的 html 文件中吗

**Comment by gwuhaolin** [comment]
目前自动生成html文件的插件还不支持自动集成Dllplugins输出的文件，这个需要自动生成html文件的插件的支持，webpack不自带自动生成html文件的功能。
