### ISSUE TITLE
2-7 文件变化监听频率有误

### ISSUE THREAD

**Issue by longxi** [gwuhaolin/dive-into-webpack#32]
https://github.com/gwuhaolin/dive-into-webpack/blob/c0851c5cc7003ebc0dd61c79b965ecf37be23c03/2%E9%85%8D%E7%BD%AE/2-7%E5%85%B6%E5%AE%83%E9%85%8D%E7%BD%AE%E9%A1%B9.html#L1194

此处应该是每秒 1 次
https://webpack.js.org/configuration/watch/#watchoptions-poll

**Comment by gwuhaolin** [comment]
谢谢指正，以修复
