### ISSUE TITLE
webpack是如何原生支持监听文件变化并自动刷新网页的

### ISSUE THREAD

**Issue by gaoguoxin** [gwuhaolin/dive-into-webpack#4]
最近买了这本书，在看到第一章1.6 使用DevServer的时候，看到作者说，webpack元亨支持监听文件的变化并自动刷新网页,做到实时预览。对于webpack原生支持监听文件变化并自动构建,这个是没有疑问的，只需要一个--watch就可以了。但是对于webpack原生支持自动刷新网页,我不知道具体怎么做,在网上找了一通,发现基本上都是webpack-dev-server通过websocket实现devServer与client通信实现刷新页面,或者是通过MHR模块热加载的方式实现实时预览。很明显，我认为通过webpack-dev-server实现的方式都不是webpack原生支持的,所以我在这里想问一下作者,webpack是怎样原生支持自动刷新网页的

**Comment by gwuhaolin** [comment]
自动刷新网页由两大步骤实现：
1. webpack 开启监听模式时会监听文件变化事件，在文件发生变化时重新构建，输出新的结果。也就是说webpack 的职责是监听文件变化和重新构建。
2. webpack-dev-server 在收到webpack发送给它的文件变化消息后，通过websocket向网页发指令，运行在网页中的代理客户端收到指令后刷新网页。也就是webpack-dev-server的职责是去控制浏览器。

详情见 [4-5使用自动刷新](http://webpack.wuhaolin.cn/4%E4%BC%98%E5%8C%96/4-5%E4%BD%BF%E7%94%A8%E8%87%AA%E5%8A%A8%E5%88%B7%E6%96%B0.html)

**Comment by gaoguoxin** [comment]
hey,你书里面说的是webpack原生支持网页自动刷新,而不是通过webpack-dev-server,按照你的解释，webpack是不能原生支持网页自动刷新的，是必须通过webpack-dev-server的，无论是通过模块热加载还是通过websocket,都是借助了webpack-dev-server，所以我觉得书里面说的webpack原生只会网页自动刷新是错误的。

**Comment by zshawk1992** [comment]
@gaoguoxin  作者没有解释错误，webpack只负责监听文件，webpack-dev-server负责刷新

**Comment by biley** [comment]
我也是看到这个问题来找 issue 的，这是 1-6 中的内容。其中原文为：

> 实际开发中你可能会需要：
> 
> 1. 提供 HTTP 服务而不是使用本地文件预览；
> 2. 监听文件的变化并自动刷新网页，做到实时预览；
> 3. 支持 Source Map，以方便调试。

以及 

> Webpack 原生支持上述第2、3点内容，再结合官方提供的开发工具 DevServer 也可以很方便地做到第1点。

其中 webpack 可以原生支持第二点是有误的。
