### ISSUE TITLE
[typo] 4-5 watchOptions.poll

### ISSUE THREAD

**Issue by susan51531** [gwuhaolin/dive-into-webpack#41]
> watchOptions.aggregateTimeout 值越大性能越好，因为这能降低重新构建的频率。
> watchOptions.poll 值**越小**越好，因为这能降低检查的频率。

poll也是值越大，频率越小

**Comment by gwuhaolin** [comment]
poll 是指每秒检查多少次，是值越大频率越大。
https://webpack.js.org/configuration/watch/#watchoptions-poll

**Comment by susan51531** [comment]
@gwuhaolin 
`
Turn on polling by passing true, or specifying a poll interval in milliseconds:
`
```js
module.exports = {
  //...
  watchOptions: {
    poll: 1000 // Check for changes every second
  }
};
```
文档说明的是interval,示例中interval是1000，为1秒，所以是每秒poll一次
是interval，并不是频率，如果是频率，上面示例就是1000次了

从[这里](https://github.com/webpack/webpack/blob/8a7597aa6eb2eef66a8f9db3a0c49bcb96022a94/hot/poll.js#L34)可以看到这个poll是直接传递给setInterval的
