### ISSUE TITLE
[typo] 5-3 但..时，..时

### ISSUE THREAD

**Issue by susan51531** [gwuhaolin/dive-into-webpack#46]
`
this.loadModule：但 Loader 在处理一个文件时，如果依赖其它文件的处理结果才能得出当前文件的结果时， 就可以通过 this.loadModule(request: string, callback: function(err, source, sourceMap, module)) 去获得 request 对应文件的处理结果。
`
可改成
`
this.loadModule：当 Loader 在处理一个文件时，如果依赖其它文件的处理结果才能得出当前文件的结果， 可以通过 this.loadModule(request: string, callback: function(err, source, sourceMap, module)) 去获得 request 对应文件的处理结果。
`

**Comment by gwuhaolin** [comment]
非常感谢您的审阅，我会全部改正。
