### ISSUE TITLE
使用webpack命令后，会报错不存在命令，提示我们安装 webpack-cli或 webpack-command

### ISSUE THREAD

**Issue by Feafortecsy** [gwuhaolin/dive-into-webpack#47]
webpack 4 里将命令行相关代码迁移出去了，所以需要安装其中之一。根据网上相关资料，选择webpack-command.命令行输入 `npm install webpack-command -g` . 此时执行`webpack`命令可成功。

**Comment by gwuhaolin** [comment]
webpack4相关内容正在重写中
