### ISSUE TITLE
4-16优化总结运行起来会报错

### ISSUE THREAD

**Issue by w3286879** [gwuhaolin/dive-into-webpack#49]
直接运行起来报错：
ERROR in ./src/pages/index/index.js
Module not found: Error: Can't resolve 'antdliutton' in 'G:\下载\4-16优化总结\src\pages\index'
 @ ./src/pages/index/index.js 11:0-37
 @ multi ./src/pages/index

ERROR in ./src/pages/index/index.js
Module not found: Error: Can't resolve 'antdliuttonstyleindex.css' in 'G:\下载\4-16优化总结\src\pages\index'
 @ ./src/pages/index/index.js 12:0-41
 @ multi ./src/pages/index

ERROR in ./src/pages/login/index.js
Module not found: Error: Can't resolve 'antdlibinput' in 'G:\下载\4-16优化总结\src\pages\login'
 @ ./src/pages/login/index.js 11:0-35
 @ multi ./src/pages/login

ERROR in ./src/pages/login/index.js
Module not found: Error: Can't resolve 'antdlibinputstyleindex.css' in 'G:\下载\4-16优化总结\src\pages\login'
 @ ./src/pages/login/index.js 12:0-40
 @ multi ./src/pages/login

**Comment by gwuhaolin** [comment]
这个 https://github.com/gwuhaolin/ui-component-loader 的一个bug
https://github.com/gwuhaolin/ui-component-loader/issues/4
已经被修复，请升级ui-component-loader版本到最新
