### ISSUE TITLE
你妈逼要开源出来就开源出来，开源出来 后面页面每个放个广告恶心人？

### ISSUE THREAD

**Issue by laozirilegoule** [gwuhaolin/dive-into-webpack#56]
我日你妈，你要开源就开源，不开源就老老实实卖钱

你妈逼你放出来，然后每个页面正中间放个广告恶心人？删除了div还js又生成？ 

你真是你妈个人才。够恶心。

**Comment by gwuhaolin** [comment]
这是出版社要求的，谢谢关注
