### ISSUE TITLE
4-1章节的webpack配置问题

### ISSUE THREAD

**Issue by baxtergu** [gwuhaolin/dive-into-webpack#58]
4-1章节的示例代码改为React16.x版本的话，`node_modules/react/dist`，`node_modules/react-dom/dist`目录是不存在的，新版本的发布包放在了`react`和`react-dom`目录下的`/umd`和`/cjs`目录下。使用示例代码中的配置引入umd包没问题，如果引入cjs包的话需要将noParse里对应的文件名正则去掉，否则会出现node环境关键字比如`require`在浏览器环境报未定义的情况。

**Comment by gwuhaolin** [comment]
谢谢指正，已补充说明。
