### ISSUE TITLE
书中的错误

### ISSUE THREAD

**Issue by gaoguoxin** [gwuhaolin/dive-into-webpack#6]
2.6.2中有提到:如果想使用DevServer的模块热替换机制,去实现实时预览,则最方便的方法是直接开启inline,这句话应该是有问题的,inline是通过websocket的方式实现的网页刷新,而不是模块热替换

**Comment by gwuhaolin** [comment]
已经修改成：
```
如果你想使用 DevServer 去自动刷新网页实现实时预览，最方便的方法是直接开启 `inline`。
```
将在下一版本修正。
