### ISSUE TITLE
3-4 使用 SCSS 接入 webpack 下的正则有误

### ISSUE THREAD

**Issue by songzeng2016** [gwuhaolin/dive-into-webpack#60]
![image](https://user-images.githubusercontent.com/21862776/53549755-06ebbf80-3b70-11e9-9d03-9cfce9cf2b74.png)
 ``` 匹配所有以 .scss 为后缀的 SCSS 文件，少了个 $ 符，/\.scss$/```
3-5 使用 PostCSS 章节有同样的问题

**Comment by gwuhaolin** [comment]
谢谢指正
