### ISSUE TITLE
第一张第五节npm i -D extract-text-webpack-plugin

### ISSUE THREAD

**Issue by bolosea** [gwuhaolin/dive-into-webpack#63]
最新安装需要装extract-text-webpack-plugin@next 
然后new ExtractTextPlugin({
      // 从 .js 文件中提取出来的 .css 文件的名称
      filename: `[name]_[contenthash:8].css`,
    }),
的contenthash 改成hash

**Comment by gwuhaolin** [comment]
为什么要把contenthash改成hash呢？
contenthash是根据文件内容计算出的摘要值，hash是根据当前构建时间计算出的摘要值，
具体想用哪个得看你的具体场景选择。
