### ISSUE TITLE
4-5 watchOptions.poll

### ISSUE THREAD

**Issue by loosenRogers** [gwuhaolin/dive-into-webpack#64]
[官网](https://webpack.js.org/configuration/watch/)中描述：
>  specifying a poll interval in milliseconds

意思是：以毫秒为单位来定义轮询的间隔，不是指一秒内轮询的次数
所以watchOptions.poll的值是越大，轮询检查的频率越低
susan51531同学已经指出了，作者为啥没采纳呢

**Comment by gwuhaolin** [comment]
谢谢指正，已修正
