### ISSUE TITLE
请问书上第23页里面的那个loaders是怎么个用法

### ISSUE THREAD

**Issue by zshawk1992** [gwuhaolin/dive-into-webpack#7]
```js
module: {
    rules: [
      {
        // 用正则去匹配要用该 loader 转换的 CSS 文件
        test: /\.css$/,
        **loaders**: ExtractTextPlugin.extract({
          // 转换 .css 文件需要使用的 Loader
          use: ['css-loader'],
        }),
      }
    ]
  }
```
里面这个loaders跟之前的use是什么关系，有的时候你用use，有时候又是loaders，书里并没有说明这个loaders

**Comment by gwuhaolin** [comment]
Webpack 官方推荐全部使用 `use`，使用 `use`和`loaders` 效果一样，`loaders`是老版本的做法，Webpack3开始使用 `use`。
我会把 `loaders` 全部换成 `use`。

**Comment by chengwenxin** [comment]
> 的是 3

执行 npm install -D extract-text-webpack-plugin@next 命令
将其更新到extract-text-webpack-plugin4.0.0-beta.0
