### ISSUE TITLE
关于电子书

### ISSUE THREAD

**Issue by ZhangDaZongWei** [gwuhaolin/dive-into-webpack#72]
作者您好，请问怎样才能看你的电子版书籍，我不想买纸质版的。

**Comment by bee0060** [comment]
本地启动一下就可以了。 例如安装http-server， 然后在项目根目录的命令行下（cmd或git bash）运行： 
```
http-server
```

会默认将项目部署到localhost:8080下，你访问localhost:8080/index.html就能看到首页。 

当然在看到后面几页的时候，有时会弹出电子版的广告， 作为要给程序员， 是有很多办法可以消除广告的。 但是毕竟作者付出了很大努力书写，我就不分享方法了。 自己可以想想办法。  

（如果作者觉得我这个教屏蔽广告的回复不恰当，请删除这条回复或提醒我修改，谢谢）

**Comment by ZhangDaZongWei** [comment]
> 本地启动一下就可以了。 例如安装http-server， 然后在项目根目录的命令行下（cmd或git bash）运行：
> 
> ```
> http-server
> ```
> 
> 会默认将项目部署到localhost:8080下，你访问localhost:8080/index.html就能看到首页。
> 
> 当然在看到后面几页的时候，有时会弹出电子版的广告， 作为要给程序员， 是有很多办法可以消除广告的。 但是毕竟作者付出了很大努力书写，我就不分享方法了。 自己可以想想办法。
> 
> （如果作者觉得我这个教屏蔽广告的回复不恰当，请删除这条回复或提醒我修改，谢谢）

谢谢你了。在这里也很感谢此书的作者，真诚地感谢。
